# Generated by Django 4.2.3 on 2023-08-11 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtopic',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='SubTopic',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
