# Generated by Django 4.2.3 on 2023-08-12 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='selected_choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.choice'),
        ),
    ]
