# Generated by Django 4.2.3 on 2023-08-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_subtopic_body_user_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
