# Generated by Django 4.2.3 on 2023-08-16 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_user_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtopic',
            name='is_completed',
        ),
    ]
