# Generated by Django 4.2.3 on 2023-08-16 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_remove_subtopic_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='is_started',
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtopic', to='Main.topic'),
        ),
    ]
