# Generated by Django 4.2.3 on 2023-08-19 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_remove_subject_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquizattempt',
            name='is_ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='test',
            name='topic',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Topics', to='Main.topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='Main.subject'),
        ),
    ]
