# Generated by Django 4.2.3 on 2023-08-19 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_userquizattempt_is_ended_alter_test_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquizattempt',
            name='percentage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userquizattempt',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_attempted_test', to='Main.test'),
        ),
    ]
