# Generated by Django 4.2.3 on 2023-10-09 13:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_userquizattempt_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_completed',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='sem',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='Main.semester'),
        ),
    ]
