# Generated by Django 5.0.1 on 2024-03-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_user_completed_created_at_alter_subject_sem'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='weightage',
            field=models.IntegerField(default=0),
        ),
    ]
