# Generated by Django 5.1.1 on 2024-12-17 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0014_topic_weightage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='test',
            name='subject',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Subject', to='Main.subject'),
        ),
    ]
