# Generated by Django 5.1.1 on 2024-12-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0016_userscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='technical_skills',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
