# Generated by Django 5.1.1 on 2024-12-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0017_userscore_technical_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='academic_skills',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userscore',
            name='backlogs',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
