# Generated by Django 5.1.1 on 2025-02-11 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0018_userscore_academic_skills_userscore_backlogs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserScore',
        ),
    ]
